categories:
  income: "Income"
  adjustment: "Adjustment"

sources:
  revolut_invest:
    file_glob: "trading-account-statement_*.xlsx"
    default_account: "REVOLUT_INVEST_ACCOUNT"

  tradernet:
    file_glob: "tradernet_table.xlsx"
    default_account: "TRADERNET_ACCOUNT"

  edenred:
    file_glob: "edenred.json"
    default_account: "EDENRED_ACCOUNT"
    categories:
      Supermercado: "Supermarket"
      Refeição: "Cafe and restaurant"
      Crédito: "Salary"

  trading_212:
    file_glob: "from_20*.csv"
    accounts:
      EUR: "TRADING212_EUR_ACCOUNT"
      USD: "TRADING212_USD_ACCOUNT"

  freedom_bank:
    file_glob: "legal_statement_*.pdf"
    default_account: "FREEDOM_BANK_ACCOUNT"
    default_category: "FREEDOM_BANK_CATEGORY"

  tinkoff_broker:
    file_glob: "Налоговый отчёт за 20*.xlsx"
    default_account: "TINKOFF_BROKER_ACCOUNT"

manual_income_placeholders:
  - account: "ACCOUNT_1"
    comment: ""
  - account: "ACCOUNT_2"
    comment: ""
  - account: "ACCOUNT_3"
    comment: ""
  - account: "ACCOUNT_4"
    comment: ""
  - account: "ACCOUNT_5"
    comment: ""
