categories:
  income: "Каша и дивы"
  adjustment: "Корректировка"

sources:
  revolut_invest:
    file_glob: "trading-account-statement_*.xlsx"
    default_account: "REVOLUT_INVEST_ACCOUNT"

  tradernet:
    file_glob: "tradernet_table.xlsx"
    default_account: "TRADERNET_ACCOUNT"

manual_income_placeholders:
  - account: "ACCOUNT_1"
    comment: ""
  - account: "ACCOUNT_2"
    comment: ""
  - account: "ACCOUNT_3"
    comment: ""
  - account: "ACCOUNT_4"
    comment: ""
  - account: "ACCOUNT_5"
    comment: ""
